version: '3'

services:
  db:
    container_name: lesson
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=lesson
      - POSTGRES_PASSWORD=lesson
      - POSTGRES_DATABASE=lesson
    command: postgres
    restart: always

  redis:
    container_name: redis-lesson
    image: redis:alpine3.14
    ports:
      - 6379:6379
